name: Tests
on: [pull_request, workflow_dispatch]
concurrency:
  group: tests-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  unit_test_job:
    name: Unit
    runs-on: macOS-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Xcode 14
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app
      - name: Install Dependencies
        run: bundle install
      - name: Run Unit Tests
        run: bundle exec fastlane unit_tests
