name: Tests
on: [pull_request, workflow_dispatch]
concurrency:
  group: tests-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  unit_test_job:
    name: Unit
    runs-on: macOS-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Xcode 14
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app
      - name: Run Unit Tests
        run: set -o pipefail && xcodebuild -workspace 'PayPal.xcworkspace' -sdk 'iphonesimulator' -configuration 'Debug' -scheme 'UnitTests' -destination 'name=iPhone 14,platform=iOS Simulator' test | xcpretty
